# Einfache Funktionen

In [71]:
import numpy as np

#x = np.sin(0); print(x)
#x = np.square(3); print(x)
# print( np.e )

# Gleichverteilung
#x = np.random.random(); print(x)

#Normalverteilung mit Erwartungswert Null und Standardabweichung 1
x = np.random.normal(10,5); print( x )


-0.9234840754413813


# Vektoren

In [79]:
import numpy as np

#Erzeugung per Hand
x = np.array( [5,6,7,8] );

#Automatisch
x = np.ones(10); print(x)
x = np.zeros(10); print(x)

#Spannender
x = np.arange(1,2,0.1); print(x)
x = np.linspace(1,2,20); print(x)

# Noch spannender...
x = np.random.random(10); print(x)
x = np.random.normal(0,1,10); print(x)



[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]
[1.         1.05263158 1.10526316 1.15789474 1.21052632 1.26315789
 1.31578947 1.36842105 1.42105263 1.47368421 1.52631579 1.57894737
 1.63157895 1.68421053 1.73684211 1.78947368 1.84210526 1.89473684
 1.94736842 2.        ]
[0.48907784 0.1864045  0.45289907 0.33407997 0.48337434 0.88398439
 0.57776178 0.77191465 0.98065028 0.02777586]
[ 0.08881351  1.54486405 -1.53458596  1.08761307  0.20510913  0.14334052
 -0.83372274  0.29956653  0.09637047  0.19639624]
